Handles SDK package rename; file -> files
hellosign/sdk-tester pull request #16
Opened 2023-01-20 00:50 UTC by jtreminio-dropbox

2023-01-20 00:54 UTC, jtreminio-dropbox commented
Failures are expected:

> Response : test_signature_request_create_embedded {'error': {'error_msg': 'Must specify file(s) to be sent.', 'error_path': 'file', 'error_name': 'bad_request'}}

2023-01-20 01:17 UTC, fenghao-chen commented
For C#, errors are `stderr=b"Unable to find image 'hellosign/dropbox-sign-dotnet:latest' locally\ndocker: Error response from daemon: pull access denied for hellosign/dropbox-sign-dotnet, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.\nSee 'docker run --help'.\n")`

For Java, errors are `stderr=b'Error: Could not find or load main class com.dropbox.sign.sdk.Requester\nCaused by: java.lang.ClassNotFoundException: com.dropbox.sign.sdk.Requester\n')`

For Python, those two account related tests failed due to `dropbox_sign.exceptions.ApiTypeError: Invalid type for variable \'account_create_request\'. Required value type is AccountCreateRequest and passed type was AccountCreateResponse at [\'account_create_request\']\n')`

The detailed error messages are hard to spot. You will need to scroll up the log quite a bit

2023-01-20 01:22 UTC, fenghao-chen requested changes

2023-01-20 01:22 UTC, fenghao-chen commented on data_java/Requester.java
> +package com.dropbox.sign_sandbox;
this should be `com.dropbox.sign.sdk`, which matches the path in docker file above

2023-01-20 01:22 UTC, fenghao-chen commented on data_python/requester.py
> +            obj = m.AccountCreateResponse.init(self._data)
should be `m.AccountCreateRequest.init(self._data)`

2023-01-20 18:16 UTC, fenghao-chen approved these changes
LGTM. Let's wait for the HelloFax release then merge this PR, so that we don't get false alarm in between

2023-01-31 17:41 UTC, fenghao-chen approved these changes
LGTM

2023-01-31 17:41 UTC, merged